Global:
  is_train: False
  epochs: 20
  save_model_dir: outputs/models
  ckpt_path: D:\project\short-term-power-forecast\outputs\models\WMSELoss_8_4_epochs20.ckpt
  seq_len: 8  # 输入的时间步长
  output_size: 4
  spacing: 15 # 采样间隔，即每个采样点为15分钟
  print_batch_step: 100
  loss_fig_flush: 5 # loss图像刷新频率
  pretrained_model:


Optimizer:
  name: Adam
  lr: 0.005

Loss:
  name: WMSELoss

PostProcess:
  name:

PreProcess:
  name: LoadSingleStationData
  pv_excel_path: D:\project\draft\pv.xlsx
  weather_excel_path: D:\project\draft\weather.xlsx
  neighbour_point:
  need_col_name: ['ds', 'weather', 'humidity', 'pressure', 'realFeel', 'pop', 'temp', 'uvi', 'windDegrees', 'windSpeed', 'windLevel']


Metric:
  name: WMAPE
  main_indicator: wmape

Architecture:
  model_type: rnn
  algorithm: CNNLSTM
  hidden_size: 42
  kernel_size: 3
  stride: 1
  dilation: 1
  num_layers: 2
  bidirectional: True

Train:
  dataset:
    name: LSTMDataSet
  loader:
    shuffle: True
    batch_size: 5 # 8
    num_workers: 0
    train_ratio: 0.9


Eval:
  start_time: '2022-09-5 00:00:00' # 预测起始时间
  end_time: '2022-09-15 23:45:00'  # 预测结束时间
  plt_show: True
  vpt: 200 # 小于该阈值采样点，不计入准确率统计

